### ISSUE TITLE
Build with --single-version-externally-managed --record record.txt

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ase-feedstock#16]
Since `setuptools` was added, this should be built with...

```
python setup.py install --single-version-externally-managed --record record.txt
```

Edit: Problem introduced in PR ( https://github.com/conda-forge/ase-feedstock/pull/10 ) as [noted here]( https://github.com/conda-forge/ase-feedstock/pull/10#pullrequestreview-84612548 ).

**Comment by jochym** [comment]
Indeed that was the cause of the problems. Thanks!.

**Comment by CJ-Wright** [comment]
@jakirkham should we put a note in the docs that we *must* have all the extra flags when building noarch?

**Comment by jochym** [comment]
I suppose so. But I am not sure if this is conclusive. I know too little about internals to state that but a warning at least should be there.

**Comment by jakirkham** [comment]
It’s not really about `noarch`, but it is about `setuptools`. We have a [note in `staged-recipes`’ FAQ]( https://github.com/conda-forge/staged-recipes/blob/master/README.md#7-when-or-why-do-i-need-to-use-python-setuppy-install---single-version-externally-managed---record-recordtxt ). Though it would be fine to have it in the docs too. If there are other ideas to help, let me know.

**Comment by jochym** [comment]
Yes, I think that this should be stressed a little bit more. I knew about these flags and use them in most of my packages but I was not aware of the level of impact they may have on final packages. I was thinking more along the lines of "garbage in the package" instead of "package not working".
