### ISSUE TITLE
AppVeyor webhook persists

### ISSUE THREAD

**Issue by jochym** [conda-forge/ase-feedstock#19]
After conversion to noarch the build on AppVeyor keeps triggering.
How to fix this? I could not find any docs on this.
Help? @conda-forge-coordinator @jakirkham ?

**Comment by jakirkham** [comment]
Sounds like issue ( https://github.com/appveyor/ci/issues/1198 ). Could you please post some details about what built and why it shouldn’t have in that issue?

Side note: @conda-forge-coordinator is a bot. Please ping `@conda-forge/core` in the future.

**Comment by jochym** [comment]
Sorry, thanks @jakirkham !
The build: https://github.com/conda-forge/ase-feedstock/pull/20
I was trying to force it to vanish but without success. We had the same problem with the production build earlier (https://github.com/conda-forge/ase-feedstock/pull/18) but since it seemed to cause no problems in actual build we have decided to merge it anyway. The package seems fine, but I do not like unexplained problems like this.

**Comment by jakirkham** [comment]
Appears the `Skip branches without appveyor.yml` setting on AppVeyor was not enabled on this feedstock. Not sure why, but readding through `staged-recipes` to correct this and any other CI settings that are out of sync.

**Comment by jakirkham** [comment]
The latest build no longer includes AppVeyor. So it appears to have fixed the issue.
