### ISSUE TITLE
3.20.1

### ISSUE THREAD

**Issue by hadim** [conda-forge/ase-feedstock#36]
It looks like 3.20.1 didnt get uploaded: https://github.com/conda-forge/ase-feedstock/commit/7d2f59e5257d3eb32a4e66850a1ee57b5750e749

It seems that the CI didn't get triggered.

**Comment by hadim** [comment]
ping @conda-forge/ase

**Comment by hadim** [comment]
@conda-forge-admin, please restart ci

**Comment by hadim** [comment]
(not sure the above works in issue but trying anyway)

**Comment by Anthchirp** [comment]
good spot. I've mentioned it on gitter, but just in case ping @conda-forge/core here, too

**Comment by beckermr** [comment]
Push an empty commit to master.

**Comment by Anthchirp** [comment]
up to @CJ-Wright or @jochym then

**Comment by beckermr** [comment]
I just pushed. Hopefully it builds.

**Comment by jochym** [comment]
There is a file on anaconda repo for 3.20.1 no (8 hour old). So I guess it got uploaded finally.
So is this fixed and we can close the issue?

**Comment by Anthchirp** [comment]
Yes, issue can be closed.
